server:
  port: 8090

spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    
  h2:
    console:
      enabled: true
      path: /h2
      
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.HSQLDialect
    show-sql: true
    
  liquibase:
    enabled: true
    change-log: classpath:/db/db_changelog.xml
    
logging:
  level:
    org.springframework.web: ERROR
    myapp.bookstore: DEBUG
  file: ${java.io.tmpdir}/application.log
  pattern.file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
eureka:
  client:
    #after applications is run it will send notification to Eureka
    initialInstanceInfoReplicationIntervalSeconds: 2
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    lease:
      duration: 5
    instance:
      preferIpAddress: true

#default netflix balancer
ribbon:
  eureka:
    enabled: true
    ReadTimeout: 2000
    ConnectTimeout: 1000
  #refreshing balancing settings
  serverlistRefreshInterval: 1000
  
feign:
  hystrix:
    enabled: true
    
