server:
  port: 8091
  #disable default white label error page and use ClientServiceErrorController instead
  error.whitelabel.enable: false

eureka:
  client:
    #after applications is run it will send notification to Eureka
    initialInstanceInfoReplicationIntervalSeconds: 2
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    lease:
      duration: 5


#default netflix balancer
ribbon:
  eureka:
    enabled: false
  #refreshing balancing settings
  serverlistRefreshInterval: 1000

spring:
  application:
    name: client-service

logging:
  level:
    org.clientservice: DEBUG
    