server:
  port: 8761

eureka:
  instance:
    #update list of servers every 1 second
    renewalThresholdUpdateIntervalMs: 1000
    #updating renewal
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

management:
  security:
    enabled: false