server:
  port: 8092
  
logging:
  level:
    org.springframework: INFO
    com.myapp.kafkaservice: DEBUG
    org.springframework.kafka.core: TRACE
    
kafka:
  bootstrap-servers: localhost:9092
  topic: author-request-dto